### ISSUE TITLE
npm tells me that I am on the wrong OS

### ISSUE THREAD

**Issue by dittodhole** [TooTallNate/node-upnp-client#8]
The issue should be clear from the output:

> npm ERR! notsup Valid OS:    linux,windows,mac
> npm ERR! notsup Valid Arch:  any
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: x64

**Comment by hedgehog1029** [comment]
You're installing the wrong package - it's `upnp-client` rather than `upnp`.
